### PR TITLE
py3 compatibility fixes

### PR DESCRIPTION
**Pull request by jbalonso**
These changes allow `xkpa` to run in python3.

### CODE REVIEW

**Comment by beala** [comment]
Sorry this took so long. Merged!

**Comment by jbalonso** [comment]
Awesome! Could, um, there be a release to pypi?

**Comment by beala** [comment]
Definitely. I'll look into it this weekend.

**Comment by beala** [comment]
Released: https://github.com/beala/xkcd-password/commit/acca3a18c18ef1b9dd7924aabede40ab61b19beb

I've only tested it on ubuntu, so please let me know if you run into issues on other platforms.

**Pull request merged**
